version: "3.7"

services:

  #Service pertama
  item-db:                  

    #Menggunakan image mongo:3 dari Docker Hub
    image: mongo:3

    #Nama container
    container_name: item-db

    #Memakai volume bernama app-db dengan target /data/db di container.
    volumes:

      - app-db:/data/db

    # Menerapkan restart policy pada berkas docker-compose.yml saran ke 2
    restart: on-failure

  #Service kedua
  item-app:                

    # Menggunakan image item-app dari GitHub Packages saran ke 4
    image : ghcr.io/sheikapraya/item-app:v1

    # Nama container
    container_name: item-app

    # Melakukan port mapping agar dapat diakses dari port 80 di host
    ports:

      - 80:8080

    # Memastikan item-app hanya berjalan setelah item-db diluncurkan
    depends_on:
     - item-db 

    # Menerapkan restart policy pada berkas docker-compose.yml saran ke 2
    restart: on-failure
    
volumes:

  app-db: