#Set versi kubernetes
apiVersion: v1

#Set kubernetes object = Secret
kind: Secret

#Set Metadata = nama & type
metadata:
  name: rabbitmq-secret
type: Opaque

#Set Data key
stringData:
  RABBIT_USERNAME: default_user_-lnSsfsAqPVDO_Uw25m
  RABBIT_PASSWORD: 4xtRNAQAU_xXgUJ9RFMeY7reqVU5BEWH