#Set versi kubernetes
apiVersion: v1

#Set kubernetes object = Service
kind: Service

#Set Metadata = nama & label
metadata:
  name: back-end
  labels:
    app: back-end
#Type network : nodeport untuk karsajobs
spec:
  type: NodePort
  selector:
    app: back-end 
  ports:
  - port: 8080
    nodePort: 31100