#Set versi kubernetes
apiVersion: v1

#Set kubernetes object = Secret
kind: Secret

#Set Metadata = nama & type
metadata:
  name: mongo-credentials
type: Opaque
#Set databese username = admin & password = supersecretpassword, base64 format
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==